<?php

return [
    '000' => ['code' => '000', 'name' => 'Banco Bankpar S.A.'],
    '001' => ['code' => '001', 'name' => 'Banco do Brasil S.A.'],
    '003' => ['code' => '003', 'name' => 'Banco da Amazônia S.A.'],
    '004' => ['code' => '004', 'name' => 'Banco do Nordeste do Brasil S.A.'],
    '021' => ['code' => '021', 'name' => 'BANESTES S.A. Banco do Estado do Espírito Santo'],
    '024' => ['code' => '024', 'name' => 'Banco de Pernambuco S.A. – BANDEPE'],
    '025' => ['code' => '025', 'name' => 'Banco Alfa S.A.'],
    '029' => ['code' => '029', 'name' => 'Banco Banerj S.A.'],
    '031' => ['code' => '031', 'name' => 'Banco Beg S.A.'],
    '033' => ['code' => '033', 'name' => 'Banco Santander (Brasil) S.A.'],
    '036' => ['code' => '036', 'name' => 'Banco Bradesco BBI S.A.'],
    '037' => ['code' => '037', 'name' => 'Banco do Estado do Pará S.A.'],
    '038' => ['code' => '038', 'name' => 'Banco Banestado S.A.'],
    '040' => ['code' => '040', 'name' => 'Banco Cargill S.A.'],
    '041' => ['code' => '041', 'name' => 'Banco do Estado do Rio Grande do Sul S.A.'],
    '044' => ['code' => '044', 'name' => 'Banco BVA S.A.'],
    '045' => ['code' => '045', 'name' => 'Banco Opportunity S.A.'],
    '047' => ['code' => '047', 'name' => 'Banco do Estado de Sergipe S.A.'],
    '062' => ['code' => '062', 'name' => 'Hipercard Banco Múltiplo S.A.'],
    '063' => ['code' => '063', 'name' => 'Banco Ibi S.A. Banco Múltiplo'],
    '065' => ['code' => '065', 'name' => 'Banco Lemon S.A.'],
    '069' => ['code' => '069', 'name' => 'BPN Brasil Banco Múltiplo S.A.'],
    '070' => ['code' => '070', 'name' => 'BRB – Banco de Brasília S.A.'],
    '072' => ['code' => '072', 'name' => 'Banco Rural Mais S.A.'],
    '073' => ['code' => '073', 'name' => 'BB Banco Popular do Brasil S.A.'],
    '074' => ['code' => '074', 'name' => 'Banco J. Safra S.A.'],
    '078' => ['code' => '078', 'name' => 'BES Investimento do Brasil S.A.-Banco de Investimento'],
    '081' => ['code' => '081', 'name' => 'Concórdia Banco S.A.'],
    '082' => ['code' => '082', 'name' => 'Banco Topázio S.A.'],
    '083' => ['code' => '083', 'name' => 'Banco da China Brasil S.A.'],
    '096' => ['code' => '096', 'name' => 'Banco BM&F de Serviços de Liquidação e Custódia S.A'],
    '104' => ['code' => '104', 'name' => 'Caixa Econômica Federal'],
    '107' => ['code' => '107', 'name' => 'Banco BBM S.A.'],
    '151' => ['code' => '151', 'name' => 'Banco Nossa Caixa S.A.'],
    '184' => ['code' => '184', 'name' => 'Banco Itaú BBA S.A.'],
    '204' => ['code' => '204', 'name' => 'Banco Bradesco Cartões S.A.'],
    '208' => ['code' => '208', 'name' => 'Banco UBS Pactual S.A.'],
    '214' => ['code' => '214', 'name' => 'Banco Dibens S.A.'],
    '215' => ['code' => '215', 'name' => 'Banco Comercial e de Investimento Sudameris S.A.'],
    '217' => ['code' => '217', 'name' => 'Banco John Deere S.A.'],
    '222' => ['code' => '222', 'name' => 'Banco Calyon Brasil S.A.'],
    '224' => ['code' => '224', 'name' => 'Banco Fibra S.A.'],
    '225' => ['code' => '225', 'name' => 'Banco Brascan S.A.'],
    '229' => ['code' => '229', 'name' => 'Banco Cruzeiro do Sul S.A.'],
    '230' => ['code' => '230', 'name' => 'Unicard Banco Múltiplo S.A.'],
    '233' => ['code' => '233', 'name' => 'Banco GE Capital S.A.'],
    '237' => ['code' => '237', 'name' => 'Banco Bradesco S.A.'],
    '246' => ['code' => '246', 'name' => 'Banco ABC Brasil S.A.'],
    '248' => ['code' => '248', 'name' => 'Banco Boavista Interatlântico S.A.'],
    '249' => ['code' => '249', 'name' => 'Banco Investcred Unibanco S.A.'],
    '250' => ['code' => '250', 'name' => 'Banco Schahin S.A.'],
    '263' => ['code' => '263', 'name' => 'Banco Cacique S.A.'],
    '265' => ['code' => '265', 'name' => 'Banco Fator S.A.'],
    '318' => ['code' => '318', 'name' => 'Banco BMG S.A.'],
    '320' => ['code' => '320', 'name' => 'Banco Industrial e Comercial S.A.'],
    '341' => ['code' => '341', 'name' => 'Banco Itaú S.A.'],
    '356' => ['code' => '356', 'name' => 'Banco Real S.A. (antigo)'],
    '366' => ['code' => '366', 'name' => 'Banco Société Générale Brasil S.A.'],
    '370' => ['code' => '370', 'name' => 'Banco WestLB do Brasil S.A.'],
    '376' => ['code' => '376', 'name' => 'Banco J. P. Morgan S.A.'],
    '389' => ['code' => '389', 'name' => 'Banco Mercantil do Brasil S.A.'],
    '394' => ['code' => '394', 'name' => 'Banco Finasa BMC S.A.'],
    '399' => ['code' => '399', 'name' => 'HSBC Bank Brasil S.A. – Banco Múltiplo'],
    '409' => ['code' => '409', 'name' => 'UNIBANCO – União de Bancos Brasileiros S.A.'],
    '422' => ['code' => '422', 'name' => 'Banco Safra S.A.'],
    '453' => ['code' => '453', 'name' => 'Banco Rural S.A.'],
    '456' => ['code' => '456', 'name' => 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.'],
    '464' => ['code' => '464', 'name' => 'Banco Sumitomo Mitsui Brasileiro S.A.'],
    '473' => ['code' => '473', 'name' => 'Banco Caixa Geral – Brasil S.A.'],
    '477' => ['code' => '477', 'name' => 'Citibank N.A.'],
    '479' => ['code' => '479', 'name' => 'Banco ItaúBank S.A'],
    '487' => ['code' => '487', 'name' => 'Deutsche Bank S.A. – Banco Alemão'],
    '488' => ['code' => '488', 'name' => 'JPMorgan Chase Bank'],
    '492' => ['code' => '492', 'name' => 'ING Bank N.V.'],
    '505' => ['code' => '505', 'name' => 'Banco Credit Suisse (Brasil) S.A.'],
    '600' => ['code' => '600', 'name' => 'Banco Luso Brasileiro S.A.'],
    '604' => ['code' => '604', 'name' => 'Banco Industrial do Brasil S.A.'],
    '610' => ['code' => '610', 'name' => 'Banco VR S.A.'],
    '611' => ['code' => '611', 'name' => 'Banco Paulista S.A.'],
    '612' => ['code' => '612', 'name' => 'Banco Guanabara S.A.'],
    '623' => ['code' => '623', 'name' => 'Banco Panamericano S.A.'],
    '626' => ['code' => '626', 'name' => 'Banco Ficsa S.A.'],
    '630' => ['code' => '630', 'name' => 'Banco Intercap S.A.'],
    '633' => ['code' => '633', 'name' => 'Banco Rendimento S.A.'],
    '634' => ['code' => '634', 'name' => 'Banco Triângulo S.A.'],
    '637' => ['code' => '637', 'name' => 'Banco Sofisa S.A.'],
    '638' => ['code' => '638', 'name' => 'Banco Prosper S.A.'],
    '641' => ['code' => '641', 'name' => 'Banco Alvorada S.A.'],
    '643' => ['code' => '643', 'name' => 'Banco Pine S.A.'],
    '652' => ['code' => '652', 'name' => 'Itaú Unibanco Holding S.A.'],
    '653' => ['code' => '653', 'name' => 'Banco Indusval S.A.'],
    '655' => ['code' => '655', 'name' => 'Banco Votorantim S.A.'],
    '707' => ['code' => '707', 'name' => 'Banco Daycoval S.A.'],
    '719' => ['code' => '719', 'name' => 'Banif-Banco Internacional do Funchal (Brasil)S.A.'],
    '734' => ['code' => '734', 'name' => 'Banco Gerdau S.A.'],
    '740' => ['code' => '740', 'name' => 'Banco Barclays S.A.'],
    '745' => ['code' => '745', 'name' => 'Banco Citibank S.A.'],
    '746' => ['code' => '746', 'name' => 'Banco Modal S.A.'],
    '747' => ['code' => '747', 'name' => 'Banco Rabobank International Brasil S.A.'],
    '748' => ['code' => '748', 'name' => 'Banco Cooperativo Sicredi S.A.'],
    '749' => ['code' => '749', 'name' => 'Banco Simples S.A.'],
    '751' => ['code' => '751', 'name' => 'Dresdner Bank Brasil S.A. – Banco Múltiplo'],
    '752' => ['code' => '752', 'name' => 'Banco BNP Paribas Brasil S.A.'],
    '755' => ['code' => '755', 'name' => 'Banco Merrill Lynch de Investimentos S.A.'],
    '756' => ['code' => '756', 'name' => 'Banco Cooperativo do Brasil S.A. – BANCOOB'],
    'M03' => ['code' => 'M03', 'name' => 'Banco Fiat S.A.'],
    'M06' => ['code' => 'M06', 'name' => 'Banco de Lage Landen Brasil S.A.'],
    'M07' => ['code' => 'M07', 'name' => 'Banco GMAC S.A.'],
    'M08' => ['code' => 'M08', 'name' => 'Banco Citicard S.A.'],
    'M09' => ['code' => 'M09', 'name' => 'Banco Itaucred Financiamentos S.A.'],
    'M11' => ['code' => 'M11', 'name' => 'Banco IBM S.A.'],
    'M14' => ['code' => 'M14', 'name' => 'Banco Volkswagen S.A.'],
    'M16' => ['code' => 'M16', 'name' => 'Banco Rodobens S.A.'],
    'M18' => ['code' => 'M18', 'name' => 'Banco Ford S.A.'],
    'M19' => ['code' => 'M19', 'name' => 'Banco CNH Capital S.A.'],
    'M20' => ['code' => 'M20', 'name' => 'Banco Toyota do Brasil S.A.'],
    'M22' => ['code' => 'M22', 'name' => 'Banco Honda S.A.'],
];